import { TestCase } from '../types';

export const COMPREHENSIVE_100_TEST_CASES: TestCase[] = [
  // HINGLISH - System & App Control (1 - 15)
  { id: 1, command: 'Pankaj Ji YouTube kholo aur music chalao', language: 'Hinglish', category: 'App Control', expectedTool: 'OpenAppTool', description: 'Opens YouTube and media player' },
  { id: 2, command: 'Phone silent kar do', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Sets device ringer to silent' },
  { id: 3, command: 'Mobile silent pe laga do', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Alternative silent mode phrasing' },
  { id: 4, command: 'Silent mode on karo', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Silent mode toggle' },
  { id: 5, command: 'Phone ko silent karna hai', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Colloquial silent mode intent' },
  { id: 6, command: 'WhatsApp kholo', language: 'Hinglish', category: 'App Control', expectedTool: 'OpenAppTool', description: 'Launches WhatsApp' },
  { id: 7, command: 'Instagram kholo', language: 'Hinglish', category: 'App Control', expectedTool: 'OpenAppTool', description: 'Launches Instagram' },
  { id: 8, command: 'Chrome kholo', language: 'Hinglish', category: 'App Control', expectedTool: 'BrowserTool', description: 'Opens Chrome browser' },
  { id: 9, command: 'Settings kholo', language: 'Hinglish', category: 'App Control', expectedTool: 'OpenAppTool', description: 'Opens Android system settings' },
  { id: 10, command: 'Camera open karo ek photo leni hai', language: 'Hinglish', category: 'Hardware', expectedTool: 'CameraTool', description: 'Launches Camera viewfinder' },
  { id: 11, command: 'Volume thoda badha do', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Increases media volume' },
  { id: 12, command: 'Torch on karo', language: 'Hinglish', category: 'Hardware', expectedTool: 'SettingsTool', description: 'Toggles flashlight torch' },
  { id: 13, command: 'WiFi settings kholo', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Opens Wi-Fi network preferences' },
  { id: 14, command: 'Bluetooth settings kholo', language: 'Hinglish', category: 'Hardware', expectedTool: 'BluetoothTool', description: 'Opens Bluetooth settings' },
  { id: 15, command: 'DND mode enable karo', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Enables Do Not Disturb' },

  // HINGLISH - Calling & Messaging (16 - 30)
  { id: 16, command: 'Rahul ko call karo', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Initiates call to Rahul with disambiguation' },
  { id: 17, command: 'Papa ko phone lagao', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Dials Papa from contacts' },
  { id: 18, command: 'Mummy ko call mila do', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Calls Mummy' },
  { id: 19, command: 'Rahul ko message bhejo ki main 10 minute mein aa raha hoon', language: 'Hinglish', category: 'Communication', expectedTool: 'MessageTool', description: 'Drafts WhatsApp message with confirmation' },
  { id: 20, command: 'Papa ko SMS karo ki main pahunch gaya', language: 'Hinglish', category: 'Communication', expectedTool: 'MessageTool', description: 'Sends SMS with arrival confirmation' },
  { id: 21, command: 'Priya ka phone number check karo', language: 'Hinglish', category: 'Communication', expectedTool: 'ContactsTool', description: 'Looks up contact details' },
  { id: 22, command: 'Office team ko message karo meeting postpone ho gayi', language: 'Hinglish', category: 'Communication', expectedTool: 'MessageTool', description: 'Prepares team broadcast message' },
  { id: 23, command: 'Last dialled number pe call karo', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Redials recent contact' },
  { id: 24, command: 'Bhai ko WhatsApp pe message bhejo urgent', language: 'Hinglish', category: 'Communication', expectedTool: 'MessageTool', description: 'Sends WhatsApp urgent alert' },
  { id: 25, command: 'Doctor Sharma ka number contacts mein dhoondho', language: 'Hinglish', category: 'Communication', expectedTool: 'ContactsTool', description: 'Searches contacts database' },
  { id: 26, command: 'Emergency number 112 dial karo', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Handles emergency helpline' },
  { id: 27, command: 'Missed calls check karo', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Checks call history' },
  { id: 28, command: 'Rahul ko call karke pucho kahan hai', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'Call intent with natural phrasing' },
  { id: 29, command: 'Mummy ko WhatsApp call lagao', language: 'Hinglish', category: 'Communication', expectedTool: 'CallTool', description: 'WhatsApp VoIP call intent' },
  { id: 30, command: 'Naya contact save karo Rohan Verma', language: 'Hinglish', category: 'Communication', expectedTool: 'ContactsTool', description: 'Adds new address book entry' },

  // HINGLISH - Alarms, Reminders & Calendar (31 - 45)
  { id: 31, command: 'Kal subah 7 baje alarm lagao', language: 'Hinglish', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Sets 7:00 AM alarm' },
  { id: 32, command: 'Shaam 6 baje mujhe call karne ka reminder dena', language: 'Hinglish', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Schedules 6:00 PM reminder' },
  { id: 33, command: 'Sunday ko 10 baje meeting remind karna', language: 'Hinglish', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Sets Sunday weekend reminder' },
  { id: 34, command: '5 minute ka timer lagao', language: 'Hinglish', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Starts 5 minute countdown' },
  { id: 35, command: 'Pankaj Ji kal 4 baje doctor meeting calendar mein add karo', language: 'Hinglish', category: 'Calendar', expectedTool: 'CalendarTool', description: 'Adds doctor visit to Calendar' },
  { id: 36, command: 'Kal subah office ke liye 7 baje remind kar dena', language: 'Hinglish', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Morning office reminder' },
  { id: 37, command: 'Aaj ka schedule kya hai calendar mein', language: 'Hinglish', category: 'Calendar', expectedTool: 'CalendarTool', description: 'Checks daily calendar schedule' },
  { id: 38, command: 'Subah 6 baje ka gym alarm set karo', language: 'Hinglish', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Sets recurring gym alarm' },
  { id: 39, command: 'Dawai lene ka reminder 2 baje ka banao', language: 'Hinglish', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Health & medicine alert' },
  { id: 40, command: 'Agli Monday client presentation calendar mein mark karo', language: 'Hinglish', category: 'Calendar', expectedTool: 'CalendarTool', description: 'Schedules business event' },
  { id: 41, command: 'Saare active alarms dikhao', language: 'Hinglish', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Lists set alarms' },
  { id: 42, command: 'Electricity bill pay karne ka reminder lagao', language: 'Hinglish', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Utility bill reminder' },
  { id: 43, command: 'Kal 3 baje interview reminder save karo', language: 'Hinglish', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Interview prep alert' },
  { id: 44, command: '15 minute ka meditation timer shuru karo', language: 'Hinglish', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Meditation timer' },
  { id: 45, command: 'Pankaj Ji kal subah weather dekh ke agar baarish hone wali ho to mujhe umbrella le jane ka reminder dena', language: 'Hinglish', category: 'Planner', expectedTool: 'WeatherTool', description: 'Multi-step intelligent condition planner' },

  // HINGLISH - Maps, Device Info & Hardware (46 - 60)
  { id: 46, command: 'Pankaj Ji Banaras Cantt ka route dikhao', language: 'Hinglish', category: 'Navigation', expectedTool: 'MapsTool', description: 'Opens navigation to Banaras Cantt' },
  { id: 47, command: 'Nearest petrol pump search karo', language: 'Hinglish', category: 'Navigation', expectedTool: 'MapsTool', description: 'Finds closest gas stations' },
  { id: 48, command: 'Airport ka route kholo', language: 'Hinglish', category: 'Navigation', expectedTool: 'MapsTool', description: 'Navigates to international airport' },
  { id: 49, command: 'Battery kitni hai?', language: 'Hinglish', category: 'Device Info', expectedTool: 'BatteryTool', description: 'Returns live battery status' },
  { id: 50, command: 'Internet connected hai kya?', language: 'Hinglish', category: 'Device Info', expectedTool: 'NetworkTool', description: 'Checks network state' },
  { id: 51, command: 'Bluetooth on hai?', language: 'Hinglish', category: 'Device Info', expectedTool: 'BluetoothTool', description: 'Checks Bluetooth adapter' },
  { id: 52, command: 'Phone ka storage kitna bacha hai?', language: 'Hinglish', category: 'Device Info', expectedTool: 'FileTool', description: 'Inspects free storage space' },
  { id: 53, command: 'Aaj ka mausam kaisa rahega?', language: 'Hinglish', category: 'Utility', expectedTool: 'WeatherTool', description: 'Retrieves current weather' },
  { id: 54, command: 'Varanasi mein baarish hogi kya aaj?', language: 'Hinglish', category: 'Utility', expectedTool: 'WeatherTool', description: 'Rain probability query' },
  { id: 55, command: 'Google Maps mein traffic check karo', language: 'Hinglish', category: 'Navigation', expectedTool: 'MapsTool', description: 'Checks traffic density' },
  { id: 56, command: 'Aas paas achha restaurant dikhao', language: 'Hinglish', category: 'Navigation', expectedTool: 'MapsTool', description: 'Nearby food exploration' },
  { id: 57, command: 'Mera phone slow chal raha hai memory check karo', language: 'Hinglish', category: 'Device Info', expectedTool: 'FileTool', description: 'RAM & storage audit' },
  { id: 58, command: 'Hotspot on karo', language: 'Hinglish', category: 'Settings', expectedTool: 'SettingsTool', description: 'Toggles mobile hotspot' },
  { id: 59, command: 'Clipboard ka text paste karo', language: 'Hinglish', category: 'System', expectedTool: 'ClipboardTool', description: 'Clipboard inspector' },
  { id: 60, command: 'Ye screen kisi ke sath share karo', language: 'Hinglish', category: 'System', expectedTool: 'ShareTool', description: 'Triggers system share sheet' },

  // PURE HINDI (61 - 80)
  { id: 61, command: 'नमस्ते जी, आप कैसे हैं?', language: 'Hindi', category: 'Conversation', expectedTool: 'None', description: 'Formal Hindi greeting' },
  { id: 62, command: 'कृपया यू-ट्यूब खोलें', language: 'Hindi', category: 'App Control', expectedTool: 'OpenAppTool', description: 'Opens YouTube politely' },
  { id: 63, command: 'मेरा फोन मूक कर दीजिए', language: 'Hindi', category: 'Settings', expectedTool: 'SettingsTool', description: 'Mutes phone in formal Hindi' },
  { id: 64, command: 'पिताजी को फोन मिलाइए', language: 'Hindi', category: 'Communication', expectedTool: 'CallTool', description: 'Dials father in pure Hindi' },
  { id: 65, command: 'माताजी को संदेश भेजें कि मैं देर से आऊंगा', language: 'Hindi', category: 'Communication', expectedTool: 'MessageTool', description: 'Sends Hindi message to mother' },
  { id: 66, command: 'प्रातः सात बजे की घंटी लगाइए', language: 'Hindi', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Hindi alarm command' },
  { id: 67, command: 'वाराणसी कैंट जाने का रास्ता दिखाइए', language: 'Hindi', category: 'Navigation', expectedTool: 'MapsTool', description: 'Hindi navigation command' },
  { id: 68, command: 'फोन में कितनी बैटरी शेष है?', language: 'Hindi', category: 'Device Info', expectedTool: 'BatteryTool', description: 'Hindi battery query' },
  { id: 69, command: 'आज वर्षा होने की कितनी संभावना है?', language: 'Hindi', category: 'Utility', expectedTool: 'WeatherTool', description: 'Hindi weather forecast' },
  { id: 70, command: 'चित्र खींचने के लिए कैमरा खोलें', language: 'Hindi', category: 'Hardware', expectedTool: 'CameraTool', description: 'Hindi camera launch' },
  { id: 71, command: 'संगीत बजाइए', language: 'Hindi', category: 'Media', expectedTool: 'MediaTool', description: 'Hindi music playback' },
  { id: 72, command: 'कल दोपहर बारह बजे की बैठक निर्धारित करें', language: 'Hindi', category: 'Calendar', expectedTool: 'CalendarTool', description: 'Hindi calendar meeting' },
  { id: 73, command: 'इंटरनेट की स्थिति क्या है?', language: 'Hindi', category: 'Device Info', expectedTool: 'NetworkTool', description: 'Hindi connectivity status' },
  { id: 74, command: 'ब्लूटूथ बंद कर दीजिए', language: 'Hindi', category: 'Hardware', expectedTool: 'BluetoothTool', description: 'Hindi Bluetooth toggle' },
  { id: 75, command: 'समीप का चिकित्सालय दिखाइए', language: 'Hindi', category: 'Navigation', expectedTool: 'MapsTool', description: 'Hindi nearby hospital search' },
  { id: 76, command: 'संदेशवाहक ऐप खोलें', language: 'Hindi', category: 'App Control', expectedTool: 'OpenAppTool', description: 'Hindi messaging app trigger' },
  { id: 77, command: 'मेरी बातचीत का इतिहास मिटाएं', language: 'Hindi', category: 'Privacy', expectedTool: 'None', description: 'Hindi privacy clearing' },
  { id: 78, command: 'स्मृति में सहेजें कि मुझे चाय पसंद है', language: 'Hindi', category: 'Memory', expectedTool: 'None', description: 'Hindi memory preference' },
  { id: 79, command: 'दस मिनट का समय नियंत्रक लगाएं', language: 'Hindi', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Hindi 10 min timer' },
  { id: 80, command: 'फोन की स्क्रीन बंद करें', language: 'Hindi', category: 'Settings', expectedTool: 'SettingsTool', description: 'Hindi lock screen intent' },

  // ENGLISH & PROFESSIONAL (81 - 100)
  { id: 81, command: 'Pankaj Ji, open YouTube and play trending music', language: 'English', category: 'App Control', expectedTool: 'OpenAppTool', description: 'English app and media intent' },
  { id: 82, command: 'Mute my device immediately', language: 'English', category: 'Settings', expectedTool: 'SettingsTool', description: 'Silent mode request' },
  { id: 83, command: 'Call Rahul Sharma on mobile', language: 'English', category: 'Communication', expectedTool: 'CallTool', description: 'Direct contact call' },
  { id: 84, command: 'Send a message to Rahul saying I am on my way', language: 'English', category: 'Communication', expectedTool: 'MessageTool', description: 'Message draft confirmation flow' },
  { id: 85, command: 'Set an alarm for 6:30 AM tomorrow', language: 'English', category: 'Alarms', expectedTool: 'AlarmTool', description: 'Morning alarm scheduler' },
  { id: 86, command: 'Remind me to take medication at 9 PM', language: 'English', category: 'Reminders', expectedTool: 'ReminderTool', description: 'Health reminder' },
  { id: 87, command: 'Show directions to Varanasi Airport on Google Maps', language: 'English', category: 'Navigation', expectedTool: 'MapsTool', description: 'Airport GPS routing' },
  { id: 88, command: 'What is the current battery percentage and health?', language: 'English', category: 'Device Info', expectedTool: 'BatteryTool', description: 'Hardware battery query' },
  { id: 89, command: 'Check my internet connection and cellular signal', language: 'English', category: 'Device Info', expectedTool: 'NetworkTool', description: 'Network diagnostics' },
  { id: 90, command: 'Schedule a doctor appointment for 4 PM on calendar', language: 'English', category: 'Calendar', expectedTool: 'CalendarTool', description: 'Google Calendar event' },
  { id: 91, command: 'Open Google Chrome and search for machine learning papers', language: 'English', category: 'Utility', expectedTool: 'BrowserTool', description: 'Browser research query' },
  { id: 92, command: 'Launch the camera to scan a document', language: 'English', category: 'Hardware', expectedTool: 'CameraTool', description: 'Camera document scan' },
  { id: 93, command: 'Pause the currently playing music', language: 'English', category: 'Media', expectedTool: 'MediaTool', description: 'Media playback pause' },
  { id: 94, command: 'How much available storage is remaining on this phone?', language: 'English', category: 'Device Info', expectedTool: 'FileTool', description: 'File storage report' },
  { id: 95, command: 'Find the nearest electric vehicle charging station', language: 'English', category: 'Navigation', expectedTool: 'MapsTool', description: 'Nearby EV station' },
  { id: 96, command: 'Check weather forecast for Varanasi today', language: 'English', category: 'Utility', expectedTool: 'WeatherTool', description: 'Weather temperature and rain' },
  { id: 97, command: 'Enable Do Not Disturb until 8 AM', language: 'English', category: 'Settings', expectedTool: 'SettingsTool', description: 'Scheduled DND profile' },
  { id: 98, command: 'Copy this address to system clipboard', language: 'English', category: 'System', expectedTool: 'ClipboardTool', description: 'Clipboard copy action' },
  { id: 99, command: 'Pankaj Ji remember that I prefer Hindi conversation', language: 'English', category: 'Memory', expectedTool: 'None', description: 'User memory update' },
  { id: 100, command: 'If it is going to rain tomorrow, remind me to carry an umbrella', language: 'English', category: 'Planner', expectedTool: 'WeatherTool', description: 'Complex condition planning workflow' }
];
